<?php

/** @var \Application\View\ViewRenderer $this */
/** @var \Auth\Model\User $currentUser */
$currentUser = $data['currentUser'];
/** @var \AddressBook\Model\Contact[] $contacts */
$contacts = $data['contacts'];

?>
<ul class="contact-group">
    <? foreach($contacts as $contact) { ?>
    <li class="contact">
        <i class="contact-title"><?= $contact->getTitle() ?></i>,
        <span class="contact-name"><?= $contact->getName() ?></span>,
        <span class="contact-email"><?= $contact->getEmail() ?></span>
        <? if (isset($currentUser)) { ?>
            <a href="#" class="contact-new" data-contact-id="<?= $contact->getId() ?>" title="Create supervised person">
                <i class="glyphicon glyphicon-plus"></i>
            </a>
            <a href="#" class="contact-delete" data-contact-id="<?= $contact->getId() ?>" title="Delete this contact">
                <i class="glyphicon glyphicon-trash"></i>
            </a>
        <? } ?>

        <? if ($contact->hasSupervisedContacts()) { ?>
            <?= $this->renderTemplate('contact-list', 'AddressBook', [
                'contacts' => $contact->getSupervisedContacts(),
            ]) ?>
        <? } ?>
    </li>
<? } ?>
</ul>
