<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Address Book</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" integrity="sha384-aUGj/X2zp5rLCbBxumKTCw2Z50WgIr1vs/PFN4praOTvYXWlVyh2UtNUU0KAUhAX" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
    <link href="/css/style.css" media="screen" rel="stylesheet" type="text/css">
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <ul class="nav navbar-nav navbar-left">
                <li class="<?= $data['pageActive']==='address-book' ? 'active' : '' ?>">
                    <a href="/"><span class="glyphicon glyphicon-book" ></span> Address book</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="<?= $data['pageActive']==='login' ? 'active' : '' ?>">
                    <a href="/login.php"><span class="glyphicon glyphicon-user" ></span> Login</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <?= $data['blockBody'] ?>
    </div>

    <footer class="footer">
        <hr>
        <div class="container">
            <p class="text-muted credit">
                <small>With <span class="text-danger">&hearts;</span> from </small>
                <a href="https://github.com/Waldz" title="Waldz">Waldz</a>
                <small>&copy; 2015</small>
            </p>
        </div>
    </footer>

</body>
</html>
