<?php

/** @var \Application\View\ViewRenderer $this */
/** @var array $errors */
$errors = $data['errors'];

?>
<form class="form-login" action="/login.php" method="post">
    <div class="form-group <?= isset($errors['email']) ? 'has-error' : '' ?>">
        <input type="text" name="email" class="form-control" placeholder="Email" value="<?= $data['inputEmail'] ?>">
        <div class="help-block with-errors"><?= isset($errors['email']) ? $errors['email'] : '' ?></div>
    </div>
    <div class="form-group <?= isset($errors['password']) ? 'has-error' : '' ?>">
        <input type="password" name="password" class="form-control" placeholder="Password">
        <div class="help-block with-errors"><?= isset($errors['password']) ? $errors['password'] : '' ?></div>
    </div>
    <button type="submit" class="btn btn-default">Login</button>
</form>
